### ISSUE TITLE
TypeError: all() received an invalid combination of arguments

### ISSUE THREAD

**Issue by mrivera42** [dlshriver/dnnf#10]
I want to get something basic running with the dnnf framework. I'm trying to verify a basic XOR gate neural network that when the two inputs are not equal, then the model should output something close to 1, and when the two inputs are equal, it should output something close to zero. Here's my code in the property file: 

```
from dnnv.properties import *
import torch

N = Network("N")
x = torch.Tensor([[0,0],[0,1],[1,0],[1,1]])

Forall(
    x,
    And(
        Implies(
            x[0] != x[1],
            N(x) > 0.9
        ),
        Implies(
            x[0] == x[1],
            N(x) < 0.1
        )
    )
)
```
Here is what I ran on the command line: 
```
$ dnnf property.py N xor.pt
```
And here is the error I got: 
```
TypeError: all() received an invalid combination of arguments - got (out=NoneType, axis=NoneType, ), but expected one of:
 * ()
 * (int dim, bool keepdim)
      didn't match because some of the keywords were incorrect: out, axis
 * (name dim, bool keepdim)
      didn't match because some of the keywords were incorrect: out, axis
```

**Comment by dlshriver** [comment]
Could you also post the output of `pip list` so I know what dependencies you have installed?

I'm not entirely sure what the issue is from the information given, but I have a few ideas. First, it looks like your network has a `.pt` extension, maybe this is just a typo, but DNNF only works with ONNX models, so make sure that you export the model to ONNX. Second, the command should be `dnnf property.py --network N xor.pt` (`--network` was missing from what you posted). Third, there is no symbolic variable in the property file, you give `x` a concrete value on line 5. DNNF tries to evaluate the property using that concrete value, and something clearly goes wrong. I'm not sure I can say much more without a network to reproduce the issue.

One final thing to note is that these tools tend to be very poor on networks with discrete input spaces, which seems to be what you are trying to do. The DNNF reduction will end up just testing every single discrete value in the input space, which is inefficient and expensive.

**Comment by mrivera42** [comment]
Did you mean to omit the x variable assignment ```x = torch.Tensor([[0,0],[0,1],[1,0],[1,1]])``` in the code block you suggested? I tried the changes you suggested, and also converted model to onnx so the new command I ran is ```dnnf property.py --network N xor.onnx```. I still get the same error though

**Comment by dlshriver** [comment]
Yes, that assignment makes x concrete. DNNF will just run the network on that single input. If there are no symbolic variables, then all DNNF does is evaluate the expression that it is given, there is nothing to falsify. In this case you get an error because we don't support evaluation with pytorch Tensors.

I did mess up the property expression slightly though. The expressions specifying that the two inputs can be either 0 or 1 must go into the implications, not the conjunction, otherwise it is saying that all values of x must be either 0 or 1, which is not true.

```
from dnnv.properties import *

N = Network("N")

Forall(
    x,
    And(
        Implies(
            And(
                Or(x[0, 0] == 0, x[0, 0] == 1),
                Or(x[0, 1] == 0, x[0, 1] == 1),
                x[0, 0] != x[0, 1],
            ),
            N(x) > 0.9,
        ),
        Implies(
            And(
                Or(x[0, 0] == 0, x[0, 0] == 1),
                Or(x[0, 1] == 0, x[0, 1] == 1),
                x[0, 0] == x[0, 1],
            ),
            N(x) < 0.1,
        ),
    ),
)
```

**Comment by mrivera42** [comment]
Well if the model wasn't trained properly, then N(x) > 0.9 would possibly not be true for the corresponding inputs and N(x) < 0.1 wouldn't either, so couldn't it be falsified? If I changed the inputs to specify a range instead of specific cases would that be more appropriate?

**Comment by dlshriver** [comment]
`x` cannot be concrete. If you specify a value for x, we just evaluate the property using that value for `x`, there is no falsification being done. I don't know what you mean by "specify a range". The constraints on `x` should be specified in the property expression. In the example I provided, it specifies that the first value in the input vector can be either 0 or 1, and the second value can be either 0 or 1 (and I assume there is a batch dimension, which is why the indices are `(0,0)` and `(0,1)`; this will depend on your specific network). Instead of specifying discrete values, you could specify an interval, e.g., `Implies(And(0 <= x <= 1, x[0,0] == x[0,1]), N(x) < 0.1)`. With the interval formulation, the property will definitely be false, but DNNF should run the falsifiers since I don't think it can currently prove that by itself.

**Comment by mrivera42** [comment]
Sorry I was using "range" and "interval" interchangeably. So if I chose an interval, why wouldn't any falsifiers be used?

**Comment by dlshriver** [comment]
What do you mean? The falsifiers won't be used if `x` is concrete. If you use the property I sent before, or modify it to use intervals like the one below, the falsifiers will be run.

```
from dnnv.properties import *

N = Network("N")

Forall(
    x,
    And(
        Implies(
            And(
                0 <= x <= 1,
                x[0, 0] != x[0, 1],
            ),
            N(x) > 0.9,
        ),
        Implies(
            And(
                0 <= x <= 1,
                x[0, 0] == x[0, 1],
            ),
            N(x) < 0.1,
        ),
    ),
)
```

**Comment by mrivera42** [comment]
That ran! Yes there's a batch dimension. And I think I understand now, there's no need to run falsifiers if you are only testing specific values. Couple of remaining questions: 
- I'm guessing ```sat``` means that the property was falsified?  
- Why ```0 <= x <= 1``` works, I'm guessing it's because the expression is evaluated for each index of x, so we don't need to write  ```0 <= x[0,0] <= 1``` and ```0 <=x[0,1]<=1``` separately. 
- What falsifier is used for this? Is there a way I can specify an adversarial attack or is that only for images?

**Comment by dlshriver** [comment]
Yes, `sat` means a violation was found. You can use the `--save-violation PATH` flag to save it as a numpy array.

`0 <= x <= 1` is equivalent to `And(0 <= x, x <= 1)`. `x` here is a symbolic tensor, whose shape is inferred from the network. The comparisons use [broadcasting](https://numpy.org/doc/stable/user/basics.broadcasting.html), just like in numpy and pytorch. Unlike numpy a comparison results in a single truth value, which is True if all values in the array satisfy the comparison and False otherwise. You can definitely specify the intervals separately, as you describe, this way just saves us a bit of typing. This isn't much of an issue here, but can be extremely helpful for large input sizes.

By default a custom PGD method is used. To use a different method, you can use the `--backend BACKEND` flag, e.g., `--backend cleverhans.projected_gradient_descent`. To see the available backends, you can use the `--long-help` option. Currently we support methods from [cleverhans](https://github.com/tensorflow/cleverhans) and [foolbox](https://github.com/bethgelab/foolbox), however these packages are not installed by default. When installing DNNF, you can specify the optional extras, as described in the [README.md](https://github.com/dlshriver/dnnf#readme), e.g., `pip install dnnf[cleverhans,foolbox]`. You should probably also be able to install them separately using pip, `pip install foolbox`.

You should be able to use any backend on any problem. The main idea of DNNF is that we will transform the problem into something the backend tools support.

**Comment by mrivera42** [comment]
The ```--save-violation PATH``` helped. Thanks for the great tool
