### ISSUE TITLE
Image Input

### ISSUE THREAD

**Issue by mrivera42** [dlshriver/dnnf#11]
I would like to run the following example property on a custom image classification model: 
```
from dnnv.properties import *
import numpy as np

N = Network("N")
x = Image(Parameter("input", type=str))
epsilon = Parameter("epsilon", float, default=1.0)

output_class = np.argmax(N(x))

Forall(
    x_,
    Implies(
        ((x - epsilon) < x_ < (x + epsilon)),
        np.argmax(N(x_)) == output_class,
    ),
)
```
But am getting the following error regarding the property input: 

```dnnv.properties.parser.errors.ParserError: No argument was provided for parameter 'input'. Try adding a command line argument '--prop.input'.```

How exactly do I use this argument and what time of format does it except? The model was converted to onnx with input shape ```(batch_size, 1, 28, 28)```

**Comment by mrivera42** [comment]
I think I would try to use one image from the torchvision MNIST dataset

**Comment by dlshriver** [comment]
It accepts paths to an image file. It can take most common image formats like png and jpeg. It can also take in a pickled numpy array (`.npy`).

`Image` is a convenience class for loading images from disk, but you can load tensors however you want. For example, if you want to use images from torchvision.datasets.MNIST, you can just import it into the property file (like in the property specified in Figure 2 of [this paper](https://dlshriver.com/assets/files/publications/CAV2021-DNNV.pdf)). You just need to convert the tensor to numpy before using it in the property expression.

For example, something like the following should work for loading MNIST images. You just have to decide which image you want to load. You could even make image_id a `Parameter` so that you can specify it on the command line.

```
from dnnv.properties import *
import numpy as np
from torchvision.datasets import MNIST
from torchvision.transforms import ToTensor

N = Network("N")
image_id = 0
# x[None] will add a batch dimension
x = MNIST("/tmp", download=True, transform=ToTensor())[image_id][0].numpy()[None]
epsilon = Parameter("epsilon", float, default=1.0)

output_class = np.argmax(N(x))

Forall(
    x_,
    Implies(
        ((x - epsilon) < x_ < (x + epsilon)),
        np.argmax(N(x_)) == output_class,
    ),
)
```

**Comment by mrivera42** [comment]
Makes a lot of sense now, thanks.
