### ISSUE TITLE
runtime issues 

### ISSUE THREAD

**Issue by mrivera42** [dlshriver/dnnf#12]
This is a follow up from earlier post I made on here about XOR model. I'm trying to write a property that can pass the falsifiers. For my XOR model, I wrote that if the input is between 0 and 1, then the output should also be between 0 and 1. 
```
from dnnv.properties import *

N = Network("N")

Forall(
    x,
    Implies(
        0 <= x <= 1,
        0 <= N(x) <= 1
    )
)
```
I expect this to pass. I ran the following : 
```
dnnf property2.py --network N xor.onnx
```
and got the following output: 
```
Falsifying: Forall(x, (((0 <= x) & (x <= 1)) ==> ((0 <= N(x)) & (N(x) <= 1))))
```
but no result yet. It's been running for several hours. I also tried to modify epsilon to a very small number (0.0001) for the MNIST example and that has been running for more than a day now with no result. Is there anything I am doing incorrectly here? Just wondering what behavior I should be expecting.

**Comment by dlshriver** [comment]
DNNF can only prove that a counter example exists, not that one doesn't. If the property is true, then DNNF will run forever using the default settings. By default we run the falsifier over and over, since the result of each run can differ due to randomness in some falsifiers (PGD in particular). You can force DNNF to give up after a certain number of tries with the `--n_starts NUMBER` flag. A higher number will give us more chances to find a counter example but will take longer before giving up. Something like 1000 is often reasonable but can be set higher or lower as you see fit.

**Comment by mrivera42** [comment]
I see, thanks for the clarification.
